spring:
  datasource:
    url: jdbc:postgresql://dpg-d1moroili9vc73cl7ppg-a.oregon-postgres.render.com:5432/pin1_wlq9
    username: pin1_wlq9_user
    password: XONQn5f5UT18Fu3CIPodOQX9K12Xfeh5
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: BancoGVM